# Generated by Django 2.2.4 on 2019-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20190927_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
