# Generated by Django 2.2.4 on 2019-10-18 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20191013_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=100)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userinfo.Article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.DeleteModel(
            name='BlogSettings',
        ),
        migrations.DeleteModel(
            name='SideBar',
        ),
    ]
