# Generated by Django 2.2.4 on 2019-10-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20191018_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
