# Generated by Django 2.2.4 on 2019-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_articleupdown_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='文章描述'),
        ),
    ]
