# Generated by Django 2.2.4 on 2019-10-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '视频名称', 'verbose_name_plural': '视频名称'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': '视频分类', 'verbose_name_plural': '视频分类'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='视频名称'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='视频分类'),
        ),
    ]
