# Generated by Django 2.2.4 on 2019-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191018_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='course',
            name='img_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
