# Generated by Django 2.2.4 on 2019-10-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20191018_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='资料名称'),
        ),
        migrations.CreateModel(
            name='Vidoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='视频名称')),
                ('profile', models.TextField()),
                ('video_url', models.URLField()),
                ('cover_url', models.URLField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='video.Course')),
            ],
        ),
    ]
